version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/api/source/conf.py

python:
  install:
    - requirements: docs/api/requirements.txt
    - method: pip
      path: .
