trame:
  cmd:
    - /opt/paraview/bin/pvpython
    - --venv
    - /deploy/server/venv
    - /deploy/SimpleCone.py
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --server
