# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  push:
    branches: [master]

  # Runs daily at midnight
  schedule:
    - cron: '30 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        working-directory: docs/vitepress
        run: "pip install -r requirements.txt"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        working-directory: docs/vitepress
        run: npm ci
      - name: Update blogs
        working-directory: docs/vitepress
        run: python update_blogs.py
      - name: Cache repo images
        uses: actions/cache@v4
        with:
          path: docs/vitepress/public/repos_images
          key: repo-images-${{ github.run_id }}
          restore-keys: |
            repo-images-
      - name: Fetch trame repos
        working-directory: docs/vitepress
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_repos.py
      - name: Build with VitePress
        working-directory: docs/vitepress
        run: |
          npm run docs:build
          touch .vitepress/dist/.nojekyll
          mkdir -p .vitepress/dist/trame
          cp -rf .vitepress/dist/logos .vitepress/dist/trame/logos
          cp -rf .vitepress/dist/assets .vitepress/dist/trame/assets

      - name: Download badges
        working-directory: docs/vitepress/.vitepress/dist
        run: |
          mkdir -p downloads
          curl -o ./downloads/trame.svg https://img.shields.io/pypi/dm/trame
          curl -o ./downloads/trame-client.svg https://img.shields.io/pypi/dm/trame-client
          curl -o ./downloads/trame-server.svg https://img.shields.io/pypi/dm/trame-server
          curl -o ./downloads/trame-common.svg https://img.shields.io/pypi/dm/trame-common
          curl -o ./downloads/trame-vuetify.svg https://img.shields.io/pypi/dm/trame-vuetify
          curl -o ./downloads/trame-vtklocal.svg https://img.shields.io/pypi/dm/trame-vtklocal
          curl -o ./downloads/trame-rca.svg https://img.shields.io/pypi/dm/trame-rca
          curl -o ./downloads/trame-vtk.svg https://img.shields.io/pypi/dm/trame-vtk
          curl -o ./downloads/trame-slicer.svg https://img.shields.io/pypi/dm/trame-slicer
          curl -o ./downloads/trame-tauri.svg https://img.shields.io/pypi/dm/trame-tauri
          curl -o ./downloads/trame-simput.svg https://img.shields.io/pypi/dm/trame-simput
          curl -o ./downloads/trame-datagrid.svg https://img.shields.io/pypi/dm/trame-datagrid
          curl -o ./downloads/trame-code.svg https://img.shields.io/pypi/dm/trame-code
          curl -o ./downloads/trame-matplotlib.svg https://img.shields.io/pypi/dm/trame-matplotlib
          curl -o ./downloads/trame-quasar.svg https://img.shields.io/pypi/dm/trame-quasar
          curl -o ./downloads/trame-image-tools.svg https://img.shields.io/pypi/dm/trame-image-tools
          curl -o ./downloads/trame-plotly.svg https://img.shields.io/pypi/dm/trame-plotly
          curl -o ./downloads/trame-iframe.svg https://img.shields.io/pypi/dm/trame-iframe
          curl -o ./downloads/trame-leaflet.svg https://img.shields.io/pypi/dm/trame-leaflet
          curl -o ./downloads/trame-vega.svg https://img.shields.io/pypi/dm/trame-vega
          curl -o ./downloads/trame-components.svg https://img.shields.io/pypi/dm/trame-components
          curl -o ./downloads/trame-deckgl.svg https://img.shields.io/pypi/dm/trame-deckgl
          curl -o ./downloads/trame-router.svg https://img.shields.io/pypi/dm/trame-router
          curl -o ./downloads/trame-markdown.svg https://img.shields.io/pypi/dm/trame-markdown
          curl -o ./downloads/trame-dataclass.svg https://img.shields.io/pypi/dm/trame-dataclass
          curl -o ./downloads/trame-xterm.svg https://img.shields.io/pypi/dm/trame-xterm
          curl -o ./downloads/trame-radial-menu.svg https://img.shields.io/pypi/dm/trame-radial-menu
          curl -o ./downloads/trame-colormaps.svg https://img.shields.io/pypi/dm/trame-colormaps
          curl -o ./downloads/trame-dockview.svg https://img.shields.io/pypi/dm/trame-dockview
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/vitepress/.vitepress/dist

  # Deployment job
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
